### PR TITLE
Improved dashboard stats documentation.

### PR DESCRIPTION
**Pull request by dennybresch**
Added more detailed information.

Hi @MrGeneration as note for you.

### CODE REVIEW

**Comment by rlue** [comment]
Hey Denny! Hope you don't find this too micromanagey—I re-edited your edits as below, trying to maximize for 1) brevity, 2) natural tone, and 3) precision:

```
The **dashboard** is the first thing you’ll see after logging in. Monitor your
productivity at a glance, compare your stats to the company average (in gray
below your own), and see what everyone else is up to.

...

Check the dashboard for a quick summary of your stats
(updated every 30 minutes).

...

+--------------------------------+------------------------------------------+
| **2. Mood**                    | How many escalated tickets do you have   |
|                                | open right now? (Mr. Bubbles gets grumpy |
|                                | if you have too many...)                 |
+--------------------------------+------------------------------------------+
| **3. Channel Distribution**    | Where are all your tickets coming from?  |
|                                | (Shows tickets created in the last seven |
|                                | days, also sorted by **inbound** vs.     |
|                                | **outbound**.)                           |
+--------------------------------+------------------------------------------+
| **4. Assigned**                | Out of all open tickets (company-wide),  |
|                                | how many are currently assigned to you?  |
+--------------------------------+------------------------------------------+
| **5. Your Tickets in Process** | What percentage of your tickets have you |
|                                | responded to or updated in the last 24   |
|                                | hours?                                   |
+--------------------------------+------------------------------------------+
| **6. Reopening Rate**          | How many of your closed tickets have     |
|                                | been re-opened in the last seven days?   |
+--------------------------------+------------------------------------------+
| **7. Activity Stream**         | What’s everyone else on your team up to? |
+--------------------------------+------------------------------------------+
```

**Comment by dennybresch** [comment]
Hi @MrGeneration 
can you please check these improvements?

**Comment by rlue** [comment]
FYI guys, I've **suggested** these changes in this thread, but I haven't actually _committed or pushed_ these changes anywhere. I can if you'd like me to, but I figured y'all should get the credit (git blame) for it.

Please let me know if you'd prefer for my name to be on these changes instead.

**Comment by dennybresch** [comment]
Hi @rlue 
thanks for this hint and flowers :)

Here is the new commit. Please take a short look and merge if everything is fine.

**Pull request merged**
