### PR TITLE
add translation files for "FR"

### PR DESCRIPTION
**Pull request by MrGeneration**
This PR provides french translation for our user docs.

### CODE REVIEW

**Comment by MrGeneration** [comment]
Should be good to go.
I already checked locally if all formattings are still functioning and fixed broken URLs.

I initially wanted to link to language specific pages of the admin documentation, however, the translation currently is at about 7% which wouldn't provide the benefits I was aiming for.

I thus changed the links back to "en" links.

**Comment by rlue** [comment]
I hate to say it, but I'm not exactly qualified to QA French language content. I assume this was not done by a human, but rather by an ML translation tool like DeepL or Google Translate? I'm going to give it my approval, with the disclaimer that **my approval should mean nothing here**—I don't know transifex, or how to compile the docs locally from RST into HTML in French, and I speak French about as well as my dogs do.

> I initially wanted to link to language specific pages of the admin documentation, however, the translation currently is at about 7% which wouldn't provide the benefits I was aiming for.

Before we go translating the admin docs into other languages, I'd like a chance to overhaul them (if I may). I know that could take a long time, though, and I'm not sure what Martin is thinking in terms of where my time could best be used to serve the company and the customers.

What are your thoughts?

**Comment by MrGeneration** [comment]
I'm requesting your approval because I have to... :D

Honestly, I don't expect your to speak, write and understand french to QA it. 
The only thing I've done is ensured that all links and formattings are working like they should.

---

Personally I currently like the user documentation as it is and wouldn't see a need to overhaul it (again) this year. That's however just my opinion and martin could think differently.

I just think you did this about one year ago and currently we're adapting to your overhaul and all changes that have come to it have run through your hands.

**Comment by MrGeneration** [comment]
Waiting for a time window on my end to merge this.

**Comment by rlue** [comment]
> I'm requesting your approval because I have to...

😂

> Personally I currently like the user documentation as it is and wouldn't see a need to overhaul it (again) this year. That's however just my opinion and martin could think differently.

Ah, I was talking about the admin (and general) docs. No serious need for an overhaul, just a fleeting thought I had!

**Comment by MrGeneration** [comment]
> Ah, I was talking about the admin (and general) docs. No serious need for an overhaul, just a fleeting 
> thought I had!

My bad - could we just have a complete documentation before breaking everything? :D

**Pull request merged**
