### PR TITLE
Fixes #124 - Partly replaced screenshots for mobile view

### LINKED ISSUE #124: Mobile View - Update "Ticket Details" screenshots
After the new design is merged, we need to update the "Ticket Details" section in [Mobile View](https://user-docs.zammad.org/en/latest/extras/mobile-view.html) documentation to reflect changes.

An example with test data looks like this: 

Screenshot_2023-06-21_at_16 38 25

### PR DESCRIPTION
**Pull request by ralf401**

### CODE REVIEW

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Looks good to me! But do you think it would be a good idea to have a screenshot in [mobile-view-notifications.png](https://github.com/zammad/zammad-user-documentation/pull/141#diff-5e747a5faadc4df1754610193d4830dc3c18af88a78f2866a5011d0ba84d8d24) without test notifications?

**Comment by dominikklein** [comment]
@ralf401 Looks like the image size is much too high compared to the old ones. Maybe you can check this?

**Comment by ralf401** [comment]
Yes you are right both :-) My browser messed up the resolution, I fixed that as well as the notification.

**Review by sheremet-va — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
